#
#

name: Merge csv files

on:
  push:
    branches: [ "data" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Git User
      run: |
         git config user.name "GitHub Action"
         git config user.email "gitHubAction@github.com"
    - name: Update Main Branch
      run: |
        git checkout main
        git fetch origin
        git merge origin/data
        git push origin main
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"        
    - name: Merge Csv
      run: python src/csvmerger.py
